### ISSUE TITLE
problem using pre trained model 

### ISSUE THREAD

**Issue by faezesaeedian** [solesensei/day2night#29]
Hello
I use "!python /content/pytorch-CycleGAN-and-pix2pix/test.py --dataroot /tmp/pitts30k/images/test/ --name day2night_pretrained --model test --no_dropout " for create day to night images with our dataset and we received this error:
AttributeError: 'Sequential' object has no attribute 'model'
how can I solve the problem?

**Comment by solesensei** [comment]
Hi, what version of Python do you run?

It's dependency issue

**Comment by solesensei** [comment]
I suggest you to try docker instead.
Or you can use virtualenv and install all project dependencies.

**Comment by solesensei** [comment]
Closed the issue due to inactivity
