### ISSUE TITLE
Question about the "name" value in data2domains.py(maybe a bug?)

### ISSUE THREAD

**Issue by Yurri-hub** [solesensei/day2night#34]
**Before your last modification in data2domains.py:**
![image](https://user-images.githubusercontent.com/50309347/203708836-d5156d6a-6859-4538-bc89-0b1b3abf3894.png)
**After the modification:**
![image](https://user-images.githubusercontent.com/50309347/203708762-c0fb6c17-93a3-43a1-b1af-ffd3c93f9b36.png)
**There is no "name" defined before "src", and the code could not run well**

**Comment by solesensei** [comment]
Thanks @Yurri-hub. It looks like a bug
