### ISSUE TITLE
could you provide the pretrained weights for cyclegan on bdd100k?

### ISSUE THREAD

**Issue by jichengyuan** [solesensei/day2night#37]
Hi,

thank you for this nice project.
When I would like to play with TestCycleGAN.ipynb, I could not find the weights for ".checkpoints/day2night/latest_net_G_A.pth" and ".checkpoints/day2night/latest_net_G_A.pth", could you provide them?

Thank you very much!

**Comment by solesensei** [comment]
Hi @jichengyuan 

Thank you for the feedback.

Unfortunately all the checkpoints are already gone. You can train your own model to get your own checkpoints.
`TestCycleGAN.ipynb` I'm afraid is not easily reproducible, it was just my example of what I got.  

Feel free to reopen, if you still have questions.
